# Site settings
title: Shannon Xu
SEOTitle: Rev. Shannon Xu | Life Coach, Intuitive Readings, Energy Healings, Spirituality, Meditations | The Psychic Dev
#header-img: img/home-bg.jpg
email: psychicdev1111@gmail.com
url: "https://psychicdev.org"              # your host, for absolute URL
description: "Not your usual psychic. Transform your life with energy healing and intuitive readings, former engineer, 能量疗愈 灵性解读 心理咨询 湾区码农"
keyword: "Shannon Xu, psychicdev, @psychic.dev, energy healing, psychic reading, past life reading, 能量疗愈, 心灵解读, 能量个案, 前世回溯, meditation, qigong, yoga, 觉醒"

contact-form: "https://docs.google.com/forms/u/0/d/e/1FAIpQLSeLqyPhlNbz4eKlAw2nTWgSkh55tW2PbrrdWD3okD7zVlMg1w/formResponse"

# Publish posts or collection documents with a future date.
future: true

# SNS settings
#RSS: false
#weibo_username:     test
#zhihu_username:     test
#github_username:    test
#twitter_username:   test
#facebook_username:  test
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
paginate_path: "/blog/page:num/"
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
#disqus_username: test

# Netease settings
#netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics 4 Properties
ga_track_id: 'G-D7YPNMDGHX'            # Format: G-xxxxxx-xx



# Sidebar settings
sidebar: false                           # whether or not using Sidebar.
sidebar-about-description: "Description of Side Bar"
sidebar-avatar: /img/avatar-sidebar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
